manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: choyuansu
      url-base: https://github.com/choyuansu
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: scotto9-zmk
      remote: choyuansu
      revision: main
  self:
    path: config
